Terraform_Scripts/vpn_user_profile/provider.tf
Terraform_Scripts/vpn_user_profile/terraform.tfvars
Terraform_Scripts/vpn_user_profile/vars.tf
Terraform_Scripts/vpn_user_profile/vpn_user_profile.tf

Updated vpn_user_profile scripts

---

Terraform_Scripts/firewall/firewall.tf
Terraform_Scripts/firewall/terraform.tfvars
Terraform_Scripts/firewall/vars.tf
Terraform_Scripts/vpn_user_profile/terraform.tfvars
Terraform_Scripts/vpn_user_profile/vpn_user_profile.tf

++ terraform.tfvars for firewall
** changed structure for firewall.tf to not be hardcoded
** updated vars.tf accordingly
++ added test cases for vpn_user_profile

Added test cases for vpn_user_profile; Updated firewall.tf

---

Terraform_Scripts/vpn_user/vars.tf
Terraform_Scripts/vpn_user/vpn_user.tf
Terraform_Scripts/vpn_user/vpn_user_testfiles/README.md
Terraform_Scripts/vpn_user/vpn_user_testfiles/changeemails.tfvars
Terraform_Scripts/vpn_user/vpn_user_testfiles/changegw.tfvars
Terraform_Scripts/vpn_user/vpn_user_testfiles/changeuser.tfvars
Terraform_Scripts/vpn_user/vpn_user_testfiles/emptycreation.tfvars
Terraform_Scripts/vpn_user_profile/vpn_user_profile_testfiles/README.md
Terraform_Scripts/vpn_user_profile/vpn_user_profile_testfiles/changename.tfvars
Terraform_Scripts/vpn_user_profile/vpn_user_profile_testfiles/emptycreation.tfvars
Terraform_Scripts/vpn_user_profile/vpn_user_profile_testfiles/removeuser.tfvars
Terraform_Scripts/vpn_user_profile/vpn_user_profile_testfiles/switchaction.tfvars
Terraform_Scripts/vpn_user_profile/vpn_user_profile_testfiles/switchport.tfvars
Terraform_Scripts/vpn_user_profile/vpn_user_profile_testfiles/switchprotocol.tfvars
Terraform_Scripts/vpn_user_profile/vpn_user_profile_testfiles/switchtarget.tfvars

** fully tested the tf functionality for vpn user and profile 
** found issues can be seen on READMEs

Added testscripts for vpn_user and vpn_profile

---

Terraform_Scripts/gateway/gateway.tf
Terraform_Scripts/peering_ha/README.md
Terraform_Scripts/peering_ha/peering_ha.tf
Terraform_Scripts/transit_network/spoke_vpc/provider.tf
Terraform_Scripts/transit_network/spoke_vpc/spoke_vpc.tf
Terraform_Scripts/transit_network/spoke_vpc/spoke_vpc_testfiles/emptycreation.tfvars
Terraform_Scripts/transit_network/spoke_vpc/terraform.tfvars
Terraform_Scripts/transit_network/spoke_vpc/vars.tf
Terraform_Scripts/transit_network/transit_vpc/provider.tf
Terraform_Scripts/transit_network/transit_vpc/terraform.tfvars
Terraform_Scripts/transit_network/transit_vpc/transit_vpc.tf
Terraform_Scripts/transit_network/transit_vpc/transit_vpc_testfiles/emptycreation.tfvars
Terraform_Scripts/transit_network/transit_vpc/vars.tf
Terraform_Scripts/transit_network/vgw_conn/provider.tf
Terraform_Scripts/transit_network/vgw_conn/terraform.tfvars
Terraform_Scripts/transit_network/vgw_conn/vars.tf
Terraform_Scripts/transit_network/vgw_conn/vgw_conn.tf
Terraform_Scripts/vpn_user/emptycreation.tfvars
Terraform_Scripts/vpn_user/terraform.tfvars
Terraform_Scripts/vpn_user/vars.tf
Terraform_Scripts/vpn_user/vpn_user.tf

++ added tag_list to various other test cases
++ added saml_endpoint test support for vpn_user
++ added test files for transit_vpc and spoke_vpc

Completed transit_vpc + spoke_vpc

---

Terraform_Scripts/firewall/firewall_testfiles/emptycreation.tfvars
Terraform_Scripts/gateway_single_az_ha/gateway.tf
Terraform_Scripts/gateway_single_az_ha/terraform.tfvars
Terraform_Scripts/gateway_single_az_ha/vars.tf
Terraform_Scripts/gateway_vpn/gateway_vpn.tf
Terraform_Scripts/gateway_vpn/gateway_vpn_testfiles/emptycreation.tfvars
Terraform_Scripts/gateway_vpn/terraform.tfvars
Terraform_Scripts/peering_ha/peering_ha_testfiles/emptycreation.tfvars
Terraform_Scripts/peering_ha/terraform.tfvars
Terraform_Scripts/vpn_user_profile/terraform.tfvars
Terraform_Scripts/vpn_user_profile/vpn_user_profile.tf
Terraform_Scripts/vpn_user_profile/vpn_user_profile_testfiles/README.md
Terraform_Scripts/vpn_user_profile/vpn_user_profile_testfiles/changename.tfvars
Terraform_Scripts/vpn_user_profile/vpn_user_profile_testfiles/emptycreation.tfvars
Terraform_Scripts/vpn_user_profile/vpn_user_profile_testfiles/removeuser.tfvars
Terraform_Scripts/vpn_user_profile/vpn_user_profile_testfiles/switchaction.tfvars
Terraform_Scripts/vpn_user_profile/vpn_user_profile_testfiles/switchport.tfvars
Terraform_Scripts/vpn_user_profile/vpn_user_profile_testfiles/switchprotocol.tfvars
Terraform_Scripts/vpn_user_profile/vpn_user_profile_testfiles/switchtarget.tfvars

** vpn_user, profile all/icmp port issue fixed
** updated test cases + formatting

vpn_user, vpn_profile, gateway

---

Terraform_Scripts/aws_tgw/aws_tgw.tf
Terraform_Scripts/aws_tgw/aws_tgw_testfiles/switchConnectDomain.tfvars
Terraform_Scripts/aws_tgw_vpc_attachment/aws_tgw_vpc_attachment.tf
Terraform_Scripts/aws_tgw_vpc_attachment/aws_tgw_vpc_attachment_testfiles/updateSecurityDomain.tfvars
Terraform_Scripts/aws_tgw_vpc_attachment/provider.tf
Terraform_Scripts/aws_tgw_vpc_attachment/terraform.tfvars
Terraform_Scripts/aws_tgw_vpc_attachment/vars.tf
Terraform_Scripts/fqdn_tag/fqdn_tag.tf
Terraform_Scripts/fqdn_tag/fqdn_tag_testfiles/README.md
Terraform_Scripts/fqdn_tag/fqdn_tag_testfiles/changeTagName.tfvars
Terraform_Scripts/fqdn_tag/fqdn_tag_testfiles/emptycreation.tfvars
Terraform_Scripts/fqdn_tag/fqdn_tag_testfiles/switchDomains.tfvars
Terraform_Scripts/fqdn_tag/fqdn_tag_testfiles/switchGW.tfvars
Terraform_Scripts/fqdn_tag/fqdn_tag_testfiles/switchMode.tfvars
Terraform_Scripts/fqdn_tag/fqdn_tag_testfiles/switchPorts.tfvars
Terraform_Scripts/fqdn_tag/fqdn_tag_testfiles/switchProtocols.tfvars
Terraform_Scripts/fqdn_tag/fqdn_tag_testfiles/switchStatus.tfvars
Terraform_Scripts/fqdn_tag/terraform.tfvars
Terraform_Scripts/transit_network/spoke_vpc/spoke_vpc.tf
Terraform_Scripts/transit_network/transit_vpc/terraform.tfvars
Terraform_Scripts/transit_network/transit_vpc/transit_vpc.tf
Terraform_Scripts/transit_network/transit_vpc/transit_vpc_testfiles/emptycreation.tfvars
Terraform_Scripts/transit_network/transit_vpc/vars.tf

Added aws_tgw_vpc_attachment testfiles, fixed dependencies for transit, spoke

---

Terraform_Scripts/controller_config/controller_config.tf
Terraform_Scripts/gateway_azure/README.md
Terraform_Scripts/gateway_azure/gateway_azure.tf
Terraform_Scripts/gateway_azure/provider.tf
Terraform_Scripts/transit_network/spoke_vpc_azure/spoke_vpc_azure.tf
Terraform_Scripts/transit_network/transit_vpc_azure/transit_vpc_azure.tf
Terraform_Scripts/version/README.md

-- deprecated vnet_resource_group_name from Azure spoke, transit
++ Azure gateway test files
-- version resource deprecation, moved to controller_config (R.11.xx)

R1.10.10 Release

---

Terraform_Scripts/gateway_azure/gateway_azure.tf
Terraform_Scripts/transit_network/vgw_conn/vgw_conn.tf
Terraform_Scripts/vpn_user_accelerator/README.md
Terraform_Scripts/vpn_user_accelerator/provider.tf
Terraform_Scripts/vpn_user_accelerator/vpn_user_accelerator.tf

Azure GW ELB fix ; vpn_user_accelerator added ; vgw_conn backend fixed

---

.gitignore

++ ignore variable files with "_cred.tfvars" formatting
** note: use this formatting to save credentials without committing to git

Update .gitignore for credentials

---

Terraform_Scripts_TF0.12/gateway_azure_insane/README.md
Terraform_Scripts_TF0.12/gateway_azure_insane/gateway_azure_insane.tf
Terraform_Scripts_TF0.12/gateway_azure_insane/provider.tf
Terraform_Scripts_TF0.12/gateway_azure_insane/vars.tf
Terraform_Scripts_TF0.12/gateway_insane/README.md
Terraform_Scripts_TF0.12/gateway_insane/gateway_insane.tf
Terraform_Scripts_TF0.12/gateway_insane/provider.tf
Terraform_Scripts_TF0.12/gateway_insane/vars.tf
Terraform_Scripts_TF0.12/spoke_gateway/spoke_gateway.tf
Terraform_Scripts_TF0.12/spoke_gateway/terraform.tfvars
Terraform_Scripts_TF0.12/spoke_gateway/updateGWSize.tfvars
Terraform_Scripts_TF0.12/spoke_gateway/updateHAGWSize.tfvars
Terraform_Scripts_TF0.12/spoke_gateway/updateTransitGW.tfvars
Terraform_Scripts_TF0.12/spoke_gateway_azure/attachTransitGW.tfvars
Terraform_Scripts_TF0.12/spoke_gateway_azure/disableSNAT.tfvars
Terraform_Scripts_TF0.12/spoke_gateway_azure/disableSingleAZHA.tfvars
Terraform_Scripts_TF0.12/spoke_gateway_azure/enableHA.tfvars
Terraform_Scripts_TF0.12/spoke_gateway_azure/spoke_gateway_azure.tf
Terraform_Scripts_TF0.12/spoke_gateway_azure/terraform.tfvars
Terraform_Scripts_TF0.12/spoke_gateway_azure/updateGWSize.tfvars
Terraform_Scripts_TF0.12/spoke_gateway_azure/updateHAGWSize.tfvars
Terraform_Scripts_TF0.12/transit_gateway_azure/disableSNAT.tfvars
Terraform_Scripts_TF0.12/transit_gateway_azure/switchConnectedTransit.tfvars
Terraform_Scripts_TF0.12/transit_gateway_azure/terraform.tfvars
Terraform_Scripts_TF0.12/transit_gateway_azure/transit_gateway_azure.tf
Terraform_Scripts_TF0.12/transit_gateway_azure/updateGWSize.tfvars
Terraform_Scripts_TF0.12/transit_gateway_azure/updateHAGWSize.tfvars

++ gateway_insane
++ gateway_azure_insane
** spoke_gateway (add insane_mode)
** transit_gateway_azure (add insane_mode)
** spoke_gateway_azure (add insane_mode)
==============

TF 0.12: Added insane_mode for AWS & ARM: gateway, transit, spoke

---

Terraform_Scripts_TF0.12/DEPRECATED/spoke_vpc/spoke_vpc.tf
Terraform_Scripts_TF0.12/DEPRECATED/transit_vpc/transit_vpc.tf
Terraform_Scripts_TF0.12/DEPRECATED/transit_vpc_firenet/transit_vpc_firenet.tf
Terraform_Scripts_TF0.12/aws_peer/terraform.tfvars
Terraform_Scripts_TF0.12/aws_tgw/aws_tgw.tf
Terraform_Scripts_TF0.12/aws_tgw_vpc_attachment/aws_tgw_vpc_attachment.tf
Terraform_Scripts_TF0.12/controller_config/disableFQDN.tfvars
Terraform_Scripts_TF0.12/controller_config/enableHTTP.tfvars
Terraform_Scripts_TF0.12/controller_config/terraform.tfvars
Terraform_Scripts_TF0.12/firewall/firewall.tf
Terraform_Scripts_TF0.12/fqdn/fqdn.tf
Terraform_Scripts_TF0.12/gateway/gateway.tf
Terraform_Scripts_TF0.12/gateway_insane/gateway_insane.tf
Terraform_Scripts_TF0.12/gateway_ldap_duo/gateway_ldap_duo.tf
Terraform_Scripts_TF0.12/gateway_okta/gateway_okta.tf
Terraform_Scripts_TF0.12/gateway_vpn/gateway_vpn.tf
Terraform_Scripts_TF0.12/site2cloud_unmapped/site2cloud_unmapped.tf
Terraform_Scripts_TF0.12/spoke_gateway/spoke_gateway.tf
Terraform_Scripts_TF0.12/trans_peer/trans_peer.tf
Terraform_Scripts_TF0.12/transit_gateway/transit_gateway.tf
Terraform_Scripts_TF0.12/transit_gateway_firenet/transit_gateway_firenet.tf
Terraform_Scripts_TF0.12/transit_gateway_peering/transit_gateway_peering.tf
Terraform_Scripts_TF0.12/tunnel/tunnel.tf
Terraform_Scripts_TF0.12/vgw_conn/vgw_conn.tf
Terraform_Scripts_TF0.12/vpc/vpc.tf
Terraform_Scripts_TF0.12/vpn_user/vpn_user.tf
Terraform_Scripts_TF0.12/vpn_user_accelerator/vpn_user_accelerator.tf

++ eip support for AWS transit and spoke
** standardized account_name for testing purposes

TF 0.12: Added allocate_new_eip, eip, ha_eip for AWS transit and spoke

---

Terraform_Scripts_TF0.12/aws_tgw/aws_tgw.tf
Terraform_Scripts_TF0.12/gateway_gcp/gateway_gcp.tf
Terraform_Scripts_TF0.12/gateway_gcp/updateHAGWSize.tfvars
Terraform_Scripts_TF0.12/spoke_gateway/spoke_gateway.tf
Terraform_Scripts_TF0.12/spoke_gateway_azure/attachTransitGW.tfvars
Terraform_Scripts_TF0.12/spoke_gateway_azure/disableSNAT.tfvars
Terraform_Scripts_TF0.12/spoke_gateway_azure/enableHA.tfvars
Terraform_Scripts_TF0.12/spoke_gateway_azure/spoke_gateway_azure.tf
Terraform_Scripts_TF0.12/spoke_gateway_azure/updateGWSize.tfvars
Terraform_Scripts_TF0.12/spoke_gateway_azure/updateHAGWSize.tfvars
Terraform_Scripts_TF0.12/spoke_gateway_gcp/disableSNAT.tfvars
Terraform_Scripts_TF0.12/spoke_gateway_gcp/enableHA.tfvars
Terraform_Scripts_TF0.12/spoke_gateway_gcp/spoke_gateway_gcp.tf
Terraform_Scripts_TF0.12/spoke_gateway_gcp/terraform.tfvars
Terraform_Scripts_TF0.12/spoke_gateway_gcp/updateGWSize.tfvars
Terraform_Scripts_TF0.12/spoke_gateway_gcp/updateHAGWSize.tfvars
Terraform_Scripts_TF0.12/transit_gateway/transit_gateway.tf
Terraform_Scripts_TF0.12/transit_gateway_azure/transit_gateway_azure.tf
Terraform_Scripts_TF0.12/transit_gateway_firenet/transit_gateway_firenet.tf
Terraform_Scripts_TF0.12/vgw_conn/vgw_conn.tf

++ (9711) Added insane-mode support for Azure gw, transit, spoke
++ (9850) Add active_mesh support for all transit resources (AWS, ARM, GCP)
++ (10304) Added Firenet/ Firewall support for TGW
++ (9419) Added vgw_conn : vgw_account, vgw_region
** Updated all GCP resources with new support sizes

TF 0.12: Release 2.2 updates

---

Terraform_Scripts_TF0.12/gateway_azure/README.md
Terraform_Scripts_TF0.12/gateway_azure/disableVPNNAT.tfvars
Terraform_Scripts_TF0.12/gateway_azure/gateway_azure.tf
Terraform_Scripts_TF0.12/gateway_azure/terraform.tfvars
Terraform_Scripts_TF0.12/gateway_azure/vars.tf
Terraform_Scripts_TF0.12/gateway_oracle_vpn/README.md
Terraform_Scripts_TF0.12/gateway_oracle_vpn/disableSingleAZHA.tfvars
Terraform_Scripts_TF0.12/gateway_oracle_vpn/disableVPNNAT.tfvars
Terraform_Scripts_TF0.12/gateway_oracle_vpn/gateway_oracle_vpn.tf
Terraform_Scripts_TF0.12/gateway_oracle_vpn/terraform.tfvars
Terraform_Scripts_TF0.12/gateway_oracle_vpn/updateCIDRs.tfvars
Terraform_Scripts_TF0.12/gateway_oracle_vpn/updateMaxConn.tfvars
Terraform_Scripts_TF0.12/gateway_oracle_vpn/updateNameServers.tfvars
Terraform_Scripts_TF0.12/gateway_oracle_vpn/updateSearchDomain.tfvars
Terraform_Scripts_TF0.12/gateway_oracle_vpn/updateVPNCIDR.tfvars
Terraform_Scripts_TF0.12/gateway_oracle_vpn/vars.tf
Terraform_Scripts_TF0.12/gateway_vpn/gateway_vpn.tf
Terraform_Scripts_TF0.12/transit_gateway_firenet/transit_gateway_firenet.tf

-- deprecate references to public_subnets in vpc resource
++ added new test cases for "enable_vpn_nat" for vpn gw

Add enable_vpn_nat test cases for non-elb gw, ARM and OCI

---

Terraform_Scripts_TF0.12/aws_tgw/aws_tgw.tf
Terraform_Scripts_TF0.12/aws_tgw_vpc_attachment/aws_tgw_vpc_attachment.tf
Terraform_Scripts_TF0.12/firewall/firewall.tf
Terraform_Scripts_TF0.12/trans_peer/trans_peer.tf
Terraform_Scripts_TF0.12/transit_gateway_peering/transit_gateway_peering.tf
Terraform_Scripts_TF0.12/tunnel/tunnel.tf
Terraform_Scripts_TF0.12/vpn_user/vpn_user.tf
Terraform_Scripts_TF0.12/vpn_user_accelerator/vpn_user_accelerator.tf

-- remove vpn gw for elb in saml_endpoint testcase (dependency issue)
-- remove explicit dependencies in various resource test cases
** cleanup

TF 0.12: Remove explicit dependencies from various test-cases

---

Regression_Testbed_TF_Module/modules/testbed-vnet-arm/main.tf

change arm vm to static public ip

change arm vm to static public ip

---

Terraform_Scripts_TF0.12/firewall/firewall.tf
Terraform_Scripts_TF0.12/firewall/stressTestPolicy.tf

++ stress test added for multi firewall policy rules
** modularized firewall gateway creation to be dynamic

TF 0.12: pull#163 added stateful_firewall stress test case

---

Regression_Testbed_TF_Module/modules/testbed-vnet-arm/main.tf

- remove denyInternet route
- add route to private subnet

fix azure private subnet in regression testbed module

---

Regression_Testbed_TF_Module/modules/testbed-aviatrix-controller/outputs.tf
Regression_Testbed_TF_Module/modules/testbed-windows-instance/outputs.tf

fix module outputs when deploy variable is false

fix module outputs when deploy variable is false

---

Terraform_Scripts_TF0.12/aws_tgw_directconnect/README.md
Terraform_Scripts_TF0.12/aws_tgw_directconnect/aws_tgw_directconnect.tf
Terraform_Scripts_TF0.12/aws_tgw_directconnect/provider.tf
Terraform_Scripts_TF0.12/aws_tgw_directconnect/terraform.tfvars
Terraform_Scripts_TF0.12/aws_tgw_directconnect/updatePrefix.tfvars
Terraform_Scripts_TF0.12/aws_tgw_directconnect/vars.tf
Terraform_Scripts_TF0.12/aws_tgw_vpc_attachment/terraform.tfvars
Terraform_Scripts_TF0.12/gateway_insane/gateway_insane.tf

++ directconnect
** fixed tgw_vpc_attachment null value input
** fixed overlapping CIDR for insane_mode gw

TF 0.12: (11644) aws_tgw_directconnect support added

---

Terraform_Scripts_TF0.12/account_awsgov/README.md
Terraform_Scripts_TF0.12/account_awsgov/account_awsgov.tf
Terraform_Scripts_TF0.12/account_awsgov/provider.tf
Terraform_Scripts_TF0.12/account_awsgov/vars.tf
Terraform_Scripts_TF0.12/aws_tgw/aws_tgw.tf
Terraform_Scripts_TF0.12/aws_tgw/enableLocalRouteProp.tfvars
Terraform_Scripts_TF0.12/aws_tgw/switchConnectDomain.tfvars
Terraform_Scripts_TF0.12/aws_tgw/switchVPC.tfvars
Terraform_Scripts_TF0.12/aws_tgw/terraform.tfvars
Terraform_Scripts_TF0.12/aws_tgw/updateCustomRoutes.tfvars

** aws_tgw stage fixed due to overlapping attached VPC between and tgw_vpc_attach stage
++ aws_gov_account support added

TF 0.12: (11644) Fix VPC attach test; (9315) AWSGov account test added

---

Terraform_Scripts_TF0.12/firenet/README.md
Terraform_Scripts_TF0.12/firenet/firenet.tf
Terraform_Scripts_TF0.12/gateway_vpn/disableSingleAZHA.tfvars
Terraform_Scripts_TF0.12/gateway_vpn/disableSplitTunnel.tfvars
Terraform_Scripts_TF0.12/gateway_vpn/disableVPNNAT.tfvars
Terraform_Scripts_TF0.12/gateway_vpn/terraform.tfvars
Terraform_Scripts_TF0.12/gateway_vpn/updateCIDRs.tfvars
Terraform_Scripts_TF0.12/gateway_vpn/updateMaxConn.tfvars
Terraform_Scripts_TF0.12/gateway_vpn/updateNameServers.tfvars
Terraform_Scripts_TF0.12/gateway_vpn/updateSearchDomain.tfvars
Terraform_Scripts_TF0.12/gateway_vpn/updateVPNCIDR.tfvars

++ firenet.tf
** vpn_gateway null implementation

TF 0.12: (11120) FireNet test case added

---

Regression_Testbed_TF_Module/modules/testbed-aviatrix-controller/main.tf
Regression_Testbed_TF_Module/modules/testbed-csr/main.tf

fix interpolation syntax, 
change tag name for csr instance 2

fix interpolation syntax, change tag name for csr instance 2

---

Terraform_Scripts_TF0.12/arm_peer/arm_peer.tf
Terraform_Scripts_TF0.12/aws_peer/aws_peer.tf
Terraform_Scripts_TF0.12/aws_tgw/aws_tgw.tf
Terraform_Scripts_TF0.12/aws_tgw_directconnect/aws_tgw_directconnect.tf
Terraform_Scripts_TF0.12/aws_tgw_vpc_attachment/aws_tgw_vpc_attachment.tf
Terraform_Scripts_TF0.12/aws_tgw_vpn_conn/aws_tgw_vpn_conn.tf
Terraform_Scripts_TF0.12/gateway_vpn/gateway_vpn.tf

++ fix for (11332) vpn_gw
++ output for resource IDs for regression importTest()

TF 0.12: Add output for resource IDs to modularize importTest()

---

Regression_Testbed_TF_Module/modules/testbed-vpc-aws/README.md
Regression_Testbed_TF_Module/modules/testbed-vpc-aws/main.tf
Regression_Testbed_TF_Module/modules/testbed-vpc-aws/variables.tf

ignore rtb changes so that when vpcs will be used for aviatrix resources, changes to the rtb won't create diffs

TF regression module: update testbed-vpc-aws

---

Regression_Testbed_TF_Module/modules/testbed-aviatrix-controller/README.md
Regression_Testbed_TF_Module/modules/testbed-aviatrix-controller/main.tf
Regression_Testbed_TF_Module/modules/testbed-aviatrix-controller/variables.tf

option to specify subnet az
deploy controller var default set to true

TF regression: controller module update

---

Terraform_Scripts_TF0.12/gateway_encrypt/README.md
Terraform_Scripts_TF0.12/gateway_encrypt/disableKey.tfvars
Terraform_Scripts_TF0.12/gateway_encrypt/gateway_encrypt.tf
Terraform_Scripts_TF0.12/gateway_encrypt/provider.tf
Terraform_Scripts_TF0.12/gateway_encrypt/vars.tf
Terraform_Scripts_TF0.12/geo_vpn/README.md
Terraform_Scripts_TF0.12/geo_vpn/geo_vpn.tf
Terraform_Scripts_TF0.12/geo_vpn/provider.tf
Terraform_Scripts_TF0.12/geo_vpn/vars.tf

** test cases are still WIP
** need dynamic references

TF 0.12: (12114) (12073) GeoVPN + Encrypt EBS support added

---

Regression_Testbed_TF_Module/modules/testbed-vnet-arm/README.md
Regression_Testbed_TF_Module/modules/testbed-vnet-arm/main.tf
Regression_Testbed_TF_Module/modules/testbed-vnet-arm/variables.tf

create 2 public subnets, 2 private subnets. 
One RT and only assocate one subnet.
RTB ignores changes made

TF Reg: update arm module

---

Regression_Testbed_TF_Module/modules/testbed-vpc-gcp/README.md
Regression_Testbed_TF_Module/modules/testbed-vpc-gcp/main.tf
Regression_Testbed_TF_Module/modules/testbed-vpc-gcp/variables.tf

Add optional variables: pri_subnet_region, pub_subnet_region, ubuntu_image
Add variable to specify ssh user
Fix subnet and zone variables to be lists of strings

TF Reg: update testbed-vpc-gcp

---

Terraform_Scripts_TF0.12/account_iam/account_iam.tf
Terraform_Scripts_TF0.12/account_iam/terraform.tfvars
Terraform_Scripts_TF0.12/account_iam/vars.tf
Terraform_Scripts_TF0.12/account_root/account_root.tf
Terraform_Scripts_TF0.12/account_root/terraform.tfvars
Terraform_Scripts_TF0.12/account_root/vars.tf
Terraform_Scripts_TF0.12/controller_config/controller_config.tf
Terraform_Scripts_TF0.12/firenet/firenet.tf
Terraform_Scripts_TF0.12/firewall/stressTestPolicy.tf
Terraform_Scripts_TF0.12/saml_endpoint/saml_endpoint.tf
Terraform_Scripts_TF0.12/site2cloud_unmapped/site2cloud_unmapped.tf
Terraform_Scripts_TF0.12/spoke_gateway_sdnat/spoke_gateway_sdnat.tf

** account_iam
** account_root
** saml_endpoint
** firewall
** firenet
** site2cloud
** importTest added controller_config
** spoke_gateway_sdnat cleaned up

TF 0.12: Update deprecated v0.11.x syntax

---

Regression_Testbed_TF_Module/modules/testbed-vpc-gcp/main.tf

add avx-snat-noip network tag to gcp private instances

TF Reg: update gcp module

---

Terraform_Scripts_TF0.12/arm_peer/README.md
Terraform_Scripts_TF0.12/arm_peer/arm_peer.tf
Terraform_Scripts_TF0.12/arm_peer/terraform.tfvars
Terraform_Scripts_TF0.12/arm_peer/vars.tf
Terraform_Scripts_TF0.12/aws_peer/README.md
Terraform_Scripts_TF0.12/aws_peer/aws_peer.tf
Terraform_Scripts_TF0.12/aws_peer/provider.tf
Terraform_Scripts_TF0.12/aws_peer/terraform.tfvars
Terraform_Scripts_TF0.12/aws_peer/vars.tf

-- removed references to hard-coded values

Update ARM and AWS peering scripts to use dynamic values

---

Terraform_Scripts_TF0.12/saml_endpoint/provider.tf
Terraform_Scripts_TF0.12/saml_endpoint/vars.tf
Terraform_Scripts_TF0.12/trans_peer/trans_peer.tf
Terraform_Scripts_TF0.12/tunnel/tunnel.tf
Terraform_Scripts_TF0.12/vgw_conn/provider.tf
Terraform_Scripts_TF0.12/vgw_conn/terraform.tfvars
Terraform_Scripts_TF0.12/vgw_conn/toggleCIDRAdvert.tfvars
Terraform_Scripts_TF0.12/vgw_conn/vars.tf
Terraform_Scripts_TF0.12/vgw_conn/vgw_conn.tf
Terraform_Scripts_TF0.12/vpc/provider.tf
Terraform_Scripts_TF0.12/vpc/vars.tf
Terraform_Scripts_TF0.12/vpn_profile/provider.tf
Terraform_Scripts_TF0.12/vpn_profile/vars.tf
Terraform_Scripts_TF0.12/vpn_user/provider.tf
Terraform_Scripts_TF0.12/vpn_user/vars.tf
Terraform_Scripts_TF0.12/vpn_user/vpn_user.tf
Terraform_Scripts_TF0.12/vpn_user_accelerator/provider.tf
Terraform_Scripts_TF0.12/vpn_user_accelerator/vars.tf

** updated vgw_conn for clean environment
** saml_endpoint, vgw_conn, vpc, vpn user/profile, accelerator now using dynamic values

Fixed invalid subnet CIDR index ref for trans_peer, tunnel

---

Terraform_Scripts_TF0.12/account_awsgov/account_awsgov.tf
Terraform_Scripts_TF0.12/account_azure/account_azure.tf
Terraform_Scripts_TF0.12/account_gcp/account_gcp.tf
Terraform_Scripts_TF0.12/account_oracle/account_oracle.tf
Terraform_Scripts_TF0.12/aws_tgw/aws_tgw.tf
Terraform_Scripts_TF0.12/aws_tgw/vars.tf
Terraform_Scripts_TF0.12/aws_tgw_vpc_attachment/README.md
Terraform_Scripts_TF0.12/aws_tgw_vpc_attachment/aws_tgw_vpc_attachment.tf
Terraform_Scripts_TF0.12/aws_tgw_vpc_attachment/terraform.tfvars
Terraform_Scripts_TF0.12/aws_tgw_vpc_attachment/updateCustomRouteAd.tfvars
Terraform_Scripts_TF0.12/aws_tgw_vpc_attachment/updateCustomRoutes.tfvars
Terraform_Scripts_TF0.12/aws_tgw_vpc_attachment/updateRouteTable.tfvars
Terraform_Scripts_TF0.12/aws_tgw_vpc_attachment/updateSecurityDomain.tfvars
Terraform_Scripts_TF0.12/aws_tgw_vpc_attachment/updateSubnets.tfvars
Terraform_Scripts_TF0.12/aws_tgw_vpc_attachment/vars.tf

** updated acc test files to remove regression bottleneck on acc creation

(12249) Added aws_tgw_vpc_attachment adv feature tests

---

Terraform_Solution_Tests/fqdn/README.md
Terraform_Solution_Tests/fqdn/fqdn.tf
Terraform_Solution_Tests/fqdn/provider_cred.tfvars
Terraform_Solution_Tests/fqdn/vars.tf
Terraform_Solution_Tests/tgw_orchestrator_with_on-prem_vgw/README.md
Terraform_Solution_Tests/tgw_orchestrator_with_on-prem_vgw/provider.tf
Terraform_Solution_Tests/tgw_orchestrator_with_on-prem_vgw/provider_cred.tfvars
Terraform_Solution_Tests/tgw_orchestrator_with_on-prem_vgw/terraform.tfvars
Terraform_Solution_Tests/tgw_orchestrator_with_on-prem_vgw/tgw_orchestrator_with_on-prem_vgw.py
Terraform_Solution_Tests/tgw_orchestrator_with_on-prem_vgw/tgw_orchestrator_with_on-prem_vgw.tf
Terraform_Solution_Tests/tgw_orchestrator_with_on-prem_vgw/vars.tf
Terraform_Solution_Tests/tgw_orchestrator_without_on-prem/README.md
Terraform_Solution_Tests/tgw_orchestrator_without_on-prem/provider.tf
Terraform_Solution_Tests/tgw_orchestrator_without_on-prem/provider_cred.tfvars
Terraform_Solution_Tests/tgw_orchestrator_without_on-prem/terraform.tfvars
Terraform_Solution_Tests/tgw_orchestrator_without_on-prem/tgw_orchestrator_without_on-prem.py
Terraform_Solution_Tests/tgw_orchestrator_without_on-prem/tgw_orchestrator_without_on-prem.tf
Terraform_Solution_Tests/tgw_orchestrator_without_on-prem/vars.tf

tgw orchestrator

---

Regression_Testbed_TF_Module/examples/example_filled.tf
Regression_Testbed_TF_Module/modules/testbed-vpc-gcp/README.md
Regression_Testbed_TF_Module/modules/testbed-vpc-gcp/variables.tf

- make pub_subnet_region and pri_subnet_region variables required

update testbed-vpc-gcp module
